### ISSUE TITLE
Saw the devcamp demo, and I was wondering...

### ISSUE THREAD

**Issue by MarkAlanJones** [profexorgeek/Glade2d#28]
Hi, I was wondering if any of the XNA code was useful as a reference. This was Microsoft's indie game platform, 10 + years ago.  .net based.   I see the archive is on GitHub https://github.com/SimonDarksideJ/XNAGameStudio 

That also points to monogame https://github.com/MonoGame/MonoGame and a number of ports, such as fna.

P.s. Add the #meadow tag to the repository, and check out some of my meadow demos, like expressivepixels, fontdemo, meadowlife, digitalrain, and meadow invaders

**Comment by profexorgeek** [comment]
Hi Mark! I built several games with XNA and contribute to the indie game engine FlatRedBall, which was originally built on MDX, then XNA, and now uses MonoGame.

Many of my ideas and approaches on Glade came from experience with projects like XNA and MonoGame, although I have to simplify a lot of things because of processing power constraints!
