### ISSUE TITLE
Performance: Render Layering

### ISSUE THREAD

**Issue by profexorgeek** [profexorgeek/Glade2d#9]
This is a container to hold a conversation that started on slack in a more public and discoverable place.

**Problem**: Rendering transparency is expensive and slow.

**Concept**: We should have a background layer that's flattened and fast, and a foreground layer that has transparency. This keeps calls that don't need transparency quick.

**Comment by KallDrexx** [comment]
# Thesis

Most 2d games have two types of graphics that are used
1. Dynamic, fast moving, independent, and heavily animated game assets. Examples of these are characters, enemies, bullets, etc...
2. Larger swaths of graphical displays that scroll, and have minor animations, but are mostly static.  Examples of these are ground textures, backgrounds, GUIs, Text UIs, etc...

Right now Glade2d only has one mechanism to display graphical assets, and that's the `Sprite` class. Using sprites for the 2nd type of graphical display is difficult from a performance and developer experience point of view. To show this we can look at a quick level from NES Mario game:

![SMB_World_2-1_NES_1](https://user-images.githubusercontent.com/139393/208182256-ad605c18-70d7-4773-88a2-27fa602a0b0b.png)

The enemies, interact-able blocks, coin, and Mario all animate and move independently, and thus it makes sense for them to be individual sprites. However, the fence panels, clouds (to some extent), ground, trees, and obstacles are all dynamic based on level data, and only move in a scrolling motion in alignment with the camera. In order to make these dynamic, the developer would need a sprite for each square tile used and manage each tile individually. 

This means every frame every individual tile must be managed (and drawn) each frame, not only by the engine but also by the developer.  

I posit that both the engine performance and developer experience can be made better by introducing the concept of Layers into Glade to solve large static-ish graphical displays.

# What Are Layers?

A layer contains graphics that can be wholly applied to the final rendered display buffer. It acts as an abstraction to make managing large intermediary image buffers / custom render targets easy, and to automatically apply these image buffers to the final display buffer in a deterministic and easy to reason about way.

A layer's underlying image buffer does not automatically get reset every frame, instead only getting partially modified as the developer applies changes to it.  Each layer can have an arbitrary height and width, and is not constrained to the dimensions of the display itself.

Layers can have segments of a texture drawn onto to them at any valid coordinate inside the bounds of the underlying image buffer. Texture segments are "stamped" onto the layer's image buffer one at a time as the developer invokes the stamping process. Each stamp is applied with transparency considered, so that transparent parts of the texture segment do not overwrite existing drawn parts of the underlying layer's image buffer.  

Each screen has a collection of background and foreground layers. Each layer in a collection is rendered to the final display in the order which they are indexed in the collection. So index of 0 is rendered first, then index 1, etc...  All background layers are rendered to the display first, then sprites in the screen's scene graph, then foreground sprites.

When a layer is drawn, no consideration is made for transparency for performance reasons.  This means if two layers overlap, the second layer will always cover a previously rendered layer regardless of the color data it contains.

# Operations Against Layers

The following is a non-comprehensive idea of operations that can be performed on layers by developers

* Reset to color
  * Completely clears the underlying  image buffer, resetting each pixel to a single specified color
* Changing layer position
  * Each layer can be given new X and Y coordinates for where it will be rendered. These can be world coordinates or relative to the camera.
* Stamp a texture segment
  * Draws the texture segment to the specified location on the underlying image buffer. This operation applies transparency based on the transparency color specified.
* Shift layer up/down/left/right
  * Shifts the pixels of the layer in the specified direction, wrapping them around
* Apply micrographics operations
  * Apply text, paths, or some other micrographics drawing to the layer

# Potential Applications

## Small Scrolling Areas

Scrolling background for relatively small areas can be created with a single layer positioned at 0,0 in world space. The layer would have a height and width of the total play area.  Upon level load the whole background would have its graphical elements stamped onto the layer in their correct positions.

As the camera moves, the layer stays in in the same spot within the world, and thus provides a scrolling effect

## Large/Infinite Scrolling Areas

Larger scrolling areas can be created with a single layer positioned at 0,0 relative to the camera. The layer would have a height and/or width that's larger than the display screen (depending on scrolling directions).  On initial level load the screen would add stamps for all the background elements within the layer's bounds (even parts that are not displayed on screen yet). As the camera moves, the layer is shifted in the opposite direction to move new parts of the layer into the camera's view.

When the camera moves a certain amount (depending on move speed, tile size, etc...), new areas of the level off screen are stamped onto the layer so they are ready when the camera attempts to display that part of the level. 

## 9 Slice UIs

A 9 slice graphical display (such as text dialogue from an RPG) can be done with the 9 slice texture segments arranged with micrographics text elements inside of it.  Slowly added dialogue can be done as well by stamping one character at a time every few frames into the text area.  This layer would be a foreground layer, so it shows over any sprites that may be on screen.

## Score and Timer HUD

Displaying the score and timer in its own foreground layer so individual digits and text elements do not need to be individually managed.  Only the changed digits need to be re-stamped when they change.
